database:
  enabled: true
  hostname: 'localhost'
  port: 27017
  creds:
    enabled: false
    username: 'root'
    password: 'password'
    database: 'revival'
broadcasts:
  enabled: true
  random: true
  interval: 60
  prefix: '&6Broadcast: &r'
chat-filter:
  enabled: true
  interval: 3
  filter-out:
    - 'nigger'
    - 'n1gger'
    - 'nigg3r'
    - 'n1gg3r'
    - 'niqqa'
    - 'nig'
    - 'n1g'
    - 'nigga'
    - 'n1gga'
    - 'nigg4'
    - 'n1gg4'
    - 'faggot'
    - 'f4ggot'
    - 'fagg0t'
    - 'f4gg0t'
    - 'fag'
    - 'f4g'
    - 'ez'
    - '3z'
    - 'gang gang'
    - 'otf'