database:
  enabled: true
  hostname: 'localhost'
  port: 27017
  creds:
    enabled: false
    username: 'root'
    password: 'password'
    database: 'revival'

tab:
  enabled: true
  header: "&aDefault Header"
  footer: "&6Default Footer"
  display-status: true

tickets:
  enabled: true
  cooldown: 30

broadcasts:
  enabled: true
  random: true
  interval: 60
  prefix: '&f[&3Revival&f] &r'

command-settings:
  disable-hub-command: false

chat-filter:
  enabled: true
  interval: 3
  filter-out:
    - 'nigger'
    - 'n1gger'
    - 'nigg3r'
    - 'n1gg3r'
    - 'niqqa'
    - 'nig'
    - 'n1g'
    - 'nigg'
    - 'n1gg'
    - 'nigga'
    - 'n1gga'
    - 'nigg4'
    - 'n1gg4'
    - 'faggot'
    - 'f4ggot'
    - 'fagg0t'
    - 'f4gg0t'
    - 'fag'
    - 'f4g'
    - 'ez'
    - '3z'
    - 'otf'

help-topics:
  factions:
    display-name: 'Factions'
    page:
        - 'Line 1'
        - 'Line 2'
        - 'Line 3'
  network:
    display-name: 'Network'
    page:
      - 'Line 1'
      - 'Line 2'
      - 'Line 3'