name: Revival
main: gg.revival.core.Revival
version: 1.0.0
author: johnsama
description: Core engine that powers the Revival Network's servers
depend: [MongoBukkitDriver, ProtocolLib]
commands:
  revival:
    description: Revival Core command
  ban:
    description: Ban a player
  tempban:
    description: Tempban a player
  unban:
    description: Unban a player
    aliases: [appeal]
  mute:
    description: Mute a player
  tempmute:
    description: Tempmute a players
  unmute:
    description: Unmute a player
  lookup:
    description: Lookup a player
    aliases: [punishments]
  enchant:
    description: Enchant an item
    aliases: [e]
  name:
    description: Name an item
    aliases: [n, rename]
  help:
    description: View help topics
  broadcast:
    description: Broadcast a message
    aliases: [b]
  kick:
    description: Kick a player from the server
  heal:
    description: Heal a player
  weather:
    description: Change the weather
  teleport:
    description: Teleport to a location
    aliases: [tp, tele]
  freeze:
    description: Freeze a player
  unfreeze:
    description: Thaw a player
    aliases: [thaw]
  hub:
    description: Return to the hub server
    aliases: [lobby]
  xp:
    description: View Revival XP
    aliases: [exp, rxp]
  message:
    description: Send a message to another player
    aliases: [msg, tell]
  reply:
    description: Respond to a player who has recently messaged you
    aliases: [r, respond]
  give:
    description: Give items
    aliases: [item, i]
  gamemode:
    description: Change gamemodes
    aliases: [gm]
  inventory:
    description: View a players inventory
    aliases: [inv]
  ignore:
    description: Block a players communications
    aliases: [block]
  unignore:
    description: Unblock a players communications
    aliases: [unblock]
  togglemessages:
    description: Toggle private messages
    aliases: [togglemsg, togglepms]
  toggleglobal:
    description: Toggle global chat
  list:
    description: List command
    aliases: [online]
  report:
    description: Report a player
    aliases: [snitch]
  helpop:
    description: Ask staff a question
    aliases: [feedback, question]
  tickets:
    description: Tickets command
    aliases: [ticket]
  vanish:
    description: Toggle vanish
    aliases: [v]
  noclip:
    description: Toggle noclip
    aliases: [nc]
  note:
    description: Leave a note on a players account